#!/usr/bin/env python

from script_sincho.exec import *
from script_sincho.basic.basic_func import logo

if __name__ == '__main__':
    logo()
    sincho_exec()
print('|======================    SINCHO Finished.    ======================|')


